-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color6 = '#8d8d8d'
local Color7 = '#F3F3F3'
local Color0 = '#5e5e5e'
local Color9 = '#FCFCFC'
local Color11 = '#f6e2e7'
local Color12 = '#e0e0e0'
local Color4 = '#B8448B'
local Color2 = '#B3003F'
local Color3 = '#206595'
local Color8 = '#262626'
local Color1 = '#9E94D5'
local Color5 = '#DB704B'
local Color10 = '#dcebe6'

highlight('Comment', nil, Color0, 'italic')
highlight('String', nil, Color1, nil)
highlight('TSCharacter', nil, Color2, nil)
highlight('Constant', nil, Color3, nil)
highlight('Number', nil, Color4, nil)
highlight('Keyword', nil, Color2, nil)
highlight('Type', nil, Color2, nil)
highlight('Function', nil, Color5, nil)
highlight('MyTag', nil, Color0, nil)
highlight('MyTag', nil, Color0, nil)
highlight('MyTag', nil, Color0, nil)
highlight('MyTag', nil, Color0, nil)
highlight('StatusLine', Color6, Color7, nil)
highlight('WildMenu', Color9, Color8, nil)
highlight('Pmenu', Color9, Color8, nil)
highlight('PmenuSel', Color8, Color9, nil)
highlight('PmenuThumb', Color9, Color8, nil)
highlight('DiffAdd', Color10, nil, nil)
highlight('DiffDelete', Color11, nil, nil)
highlight('Normal', Color9, Color8, nil)
highlight('Visual', Color12, nil, nil)
highlight('CursorLine', Color12, nil, nil)
highlight('ColorColumn', Color12, nil, nil)
highlight('SignColumn', Color9, nil, nil)
highlight('LineNr', nil, Color6, nil)
highlight('TabLine', Color7, Color0, nil)
highlight('TabLineSel', Color8, Color9, nil)
highlight('TabLineFill', Color7, Color0, nil)
highlight('TSPunctDelimiter', nil, Color8, nil)

link('TSFloat', 'Number')
link('TSConditional', 'Conditional')
link('TSFunction', 'Function')
link('TSField', 'Constant')
link('Repeat', 'Conditional')
link('TSOperator', 'Operator')
link('TSTagDelimiter', 'Type')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSParameterReference', 'TSParameter')
link('TSNamespace', 'TSType')
link('TSType', 'Type')
link('TSFuncMacro', 'Macro')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('NonText', 'Comment')
link('TSConstant', 'Constant')
link('TSRepeat', 'Repeat')
link('TSComment', 'Comment')
link('Conditional', 'Operator')
link('Folded', 'Comment')
link('Whitespace', 'Comment')
link('TSParameter', 'Constant')
link('TSProperty', 'TSField')
link('TSNumber', 'Number')
link('TSTag', 'MyTag')
link('CursorLineNr', 'Identifier')
link('Operator', 'Keyword')
link('Macro', 'Function')
link('TSLabel', 'Type')
link('TSPunctBracket', 'MyTag')
link('TelescopeNormal', 'Normal')
link('TSString', 'String')
link('TSKeyword', 'Keyword')
