-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color4 = '#82d2ce'
local Color8 = '#181818'
local Color0 = '#e394dc'
local Color12 = '#303030'
local Color13 = '#4c4c4c'
local Color1 = '#d6d6dd'
local Color9 = '#d4d4d4'
local Color5 = '#ebc88d'
local Color2 = '#82D2CE'
local Color6 = '#636363'
local Color7 = '#141414'
local Color10 = '#1d2a22'
local Color11 = '#2d141e'
local Color3 = '#efb080'

highlight('String', nil, Color0, nil)
highlight('Operator', nil, Color1, nil)
highlight('Keyword', nil, Color2, nil)
highlight('Identifier', nil, Color1, nil)
highlight('Function', nil, Color3, nil)
highlight('Type', nil, Color3, nil)
highlight('Type', nil, Color4, nil)
highlight('Number', nil, Color5, nil)
highlight('StatusLine', Color6, Color7, nil)
highlight('WildMenu', Color8, Color9, nil)
highlight('Pmenu', Color8, Color9, nil)
highlight('PmenuSel', Color9, Color8, nil)
highlight('PmenuThumb', Color8, Color9, nil)
highlight('DiffAdd', Color10, nil, nil)
highlight('DiffDelete', Color11, nil, nil)
highlight('Normal', Color8, Color9, nil)
highlight('Visual', Color12, nil, nil)
highlight('CursorLine', Color12, nil, nil)
highlight('ColorColumn', Color12, nil, nil)
highlight('SignColumn', Color8, nil, nil)
highlight('LineNr', nil, Color13, nil)
highlight('TabLine', Color7, Color13, nil)
highlight('TabLineSel', Color9, Color8, nil)
highlight('TabLineFill', Color7, Color13, nil)
highlight('TSPunctDelimiter', nil, Color9, nil)

link('TSRepeat', 'Repeat')
link('TSLabel', 'Type')
link('TSField', 'Constant')
link('CursorLineNr', 'Identifier')
link('TSTag', 'MyTag')
link('TSNamespace', 'TSType')
link('TSKeyword', 'Keyword')
link('TSParameter', 'Constant')
link('TSNumber', 'Number')
link('Conditional', 'Operator')
link('TSComment', 'Comment')
link('TSOperator', 'Operator')
link('TSFunction', 'Function')
link('TSPunctBracket', 'MyTag')
link('TSString', 'String')
link('Operator', 'Keyword')
link('TSFloat', 'Number')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TelescopeNormal', 'Normal')
link('TSTagDelimiter', 'Type')
link('TSFuncMacro', 'Macro')
link('TSType', 'Type')
link('TSParameterReference', 'TSParameter')
link('Folded', 'Comment')
link('Repeat', 'Conditional')
link('Macro', 'Function')
link('TSProperty', 'TSField')
link('Whitespace', 'Comment')
link('NonText', 'Comment')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSConditional', 'Conditional')
link('TSConstant', 'Constant')
