local M = {}

function M.apply(c)
  local hl = function(group, opts)
    vim.api.nvim_set_hl(0, group, opts)
  end

  hl("Normal", { fg = c.fg, bg = c.bg })
  hl("NormalFloat", { fg = c.fg, bg = c.bg_elevated })
  hl("FloatBorder", { fg = c.border, bg = c.bg_elevated })
  hl("FloatTitle", { fg = c.accent, bg = c.bg_elevated })
  hl("Cursor", { fg = c.bg, bg = c.accent })
  hl("CursorLine", { bg = c.bg_hover })
  hl("CursorLineNr", { fg = c.line_nr_active })
  hl("LineNr", { fg = c.line_nr })
  hl("SignColumn", { bg = c.bg })
  hl("VertSplit", { fg = c.border })
  hl("WinSeparator", { fg = c.border })
  hl("StatusLine", { fg = c.fg_muted, bg = c.bg })
  hl("StatusLineNC", { fg = c.fg_dim, bg = c.bg })
  hl("TabLine", { fg = c.fg_muted, bg = c.bg })
  hl("TabLineFill", { bg = c.bg })
  hl("TabLineSel", { fg = c.fg, bg = c.bg_elevated })
  hl("Pmenu", { fg = c.fg, bg = c.bg_elevated })
  hl("PmenuSel", { fg = c.fg, bg = c.bg_selected })
  hl("PmenuSbar", { bg = c.bg_elevated })
  hl("PmenuThumb", { bg = c.bg_hover })
  hl("Visual", { bg = c.bg_hover })
  hl("Search", { fg = c.fg, bg = c.search })
  hl("IncSearch", { fg = c.bg, bg = c.accent })
  hl("CurSearch", { fg = c.bg, bg = c.accent })
  hl("MatchParen", { fg = c.accent, bg = c.bg_hover })
  hl("Folded", { fg = c.fg_muted, bg = c.bg_elevated })
  hl("FoldColumn", { fg = c.fg_dim, bg = c.bg })
  hl("NonText", { fg = c.fg_dim })
  hl("SpecialKey", { fg = c.fg_dim })
  hl("Whitespace", { fg = c.fg_dim })
  hl("EndOfBuffer", { fg = c.bg })
  hl("Directory", { fg = c.accent })
  hl("Question", { fg = c.accent })
  hl("MoreMsg", { fg = c.accent })
  hl("ModeMsg", { fg = c.fg_muted })
  hl("ErrorMsg", { fg = c.error or c.fg })
  hl("WarningMsg", { fg = c.warning or c.accent })
  hl("Title", { fg = c.accent })
  hl("WildMenu", { fg = c.fg, bg = c.bg_selected })

  hl("Comment", { fg = c.comment })
  hl("Constant", { fg = c.constant or c.accent })
  hl("String", { fg = c.string })
  hl("Character", { fg = c.char or c.string })
  hl("Number", { fg = c.number or c.accent })
  hl("Boolean", { fg = c.accent })
  hl("Float", { fg = c.number or c.accent })
  hl("Identifier", { fg = c.fg })
  hl("Function", { fg = c.accent })
  hl("Statement", { fg = c.keyword })
  hl("Conditional", { fg = c.keyword })
  hl("Repeat", { fg = c.keyword })
  hl("Label", { fg = c.accent })
  hl("Operator", { fg = c.keyword })
  hl("Keyword", { fg = c.keyword })
  hl("Exception", { fg = c.keyword })
  hl("PreProc", { fg = c.keyword })
  hl("Include", { fg = c.keyword })
  hl("Define", { fg = c.keyword })
  hl("Macro", { fg = c.accent })
  hl("PreCondit", { fg = c.keyword })
  hl("Type", { fg = c.accent })
  hl("StorageClass", { fg = c.keyword })
  hl("Structure", { fg = c.accent })
  hl("Typedef", { fg = c.accent })
  hl("Special", { fg = c.accent })
  hl("SpecialChar", { fg = c.accent })
  hl("Tag", { fg = c.accent })
  hl("Delimiter", { fg = c.fg_muted })
  hl("SpecialComment", { fg = c.comment })
  hl("Debug", { fg = c.error or c.fg })
  hl("Underlined", { fg = c.accent, underline = true })
  hl("Error", { fg = c.error or c.fg })
  hl("Todo", { fg = c.accent, bg = c.bg_elevated })

  if c.error then
    hl("DiagnosticError", { fg = c.error })
    hl("DiagnosticUnderlineError", { sp = c.error, undercurl = true })
    hl("DiagnosticVirtualTextError", { fg = c.error, bg = c.bg })
    hl("DiagnosticFloatingError", { fg = c.error })
    hl("DiagnosticSignError", { fg = c.error })
  end

  if c.warning then
    hl("DiagnosticWarn", { fg = c.warning })
    hl("DiagnosticUnderlineWarn", { sp = c.warning, undercurl = true })
    hl("DiagnosticVirtualTextWarn", { fg = c.warning, bg = c.bg })
    hl("DiagnosticFloatingWarn", { fg = c.warning })
    hl("DiagnosticSignWarn", { fg = c.warning })
  end

  if c.info then
    hl("DiagnosticInfo", { fg = c.info })
    hl("DiagnosticUnderlineInfo", { sp = c.info, undercurl = true })
    hl("DiagnosticVirtualTextInfo", { fg = c.info, bg = c.bg })
    hl("DiagnosticFloatingInfo", { fg = c.info })
    hl("DiagnosticSignInfo", { fg = c.info })
  end

  if c.hint then
    hl("DiagnosticHint", { fg = c.hint })
    hl("DiagnosticUnderlineHint", { sp = c.hint, undercurl = true })
    hl("DiagnosticVirtualTextHint", { fg = c.hint, bg = c.bg })
    hl("DiagnosticFloatingHint", { fg = c.hint })
    hl("DiagnosticSignHint", { fg = c.hint })
  end

  hl("LspReferenceText", { bg = c.bg_hover })
  hl("LspReferenceRead", { bg = c.bg_hover })
  hl("LspReferenceWrite", { bg = c.bg_hover })
  hl("LspSignatureActiveParameter", { fg = c.accent })
  hl("LspInlayHint", { fg = c.fg_dim, bg = c.bg })

  if c.bg_diff_add then
    hl("DiffAdd", { bg = c.bg_diff_add })
  elseif c.added then
    hl("DiffAdd", { fg = c.added, bg = c.bg })
  end

  if c.bg_diff_delete then
    hl("DiffDelete", { bg = c.bg_diff_delete })
  elseif c.deleted then
    hl("DiffDelete", { fg = c.deleted, bg = c.bg })
  end

  if c.changed then
    hl("DiffChange", { fg = c.changed, bg = c.bg })
    hl("DiffText", { fg = c.changed, bg = c.bg_hover })
  end

  if c.added then
    hl("Added", { fg = c.added })
    hl("GitSignsAdd", { fg = c.added })
    hl("MiniDiffSignAdd", { fg = c.added })
    hl("MiniDiffOverAdd", { fg = c.added, bg = c.bg })
  end

  if c.changed then
    hl("Changed", { fg = c.changed })
    hl("GitSignsChange", { fg = c.changed })
    hl("MiniDiffSignChange", { fg = c.changed })
    hl("MiniDiffOverChange", { fg = c.changed, bg = c.bg })
  end

  if c.deleted then
    hl("Removed", { fg = c.deleted })
    hl("GitSignsDelete", { fg = c.deleted })
    hl("MiniDiffSignDelete", { fg = c.deleted })
    hl("MiniDiffOverDelete", { fg = c.deleted, bg = c.bg })
  end

  hl("MiniStatuslineDevinfo", { fg = c.fg_muted, bg = c.bg })
  hl("MiniStatuslineFileinfo", { fg = c.fg_muted, bg = c.bg })
  hl("MiniStatuslineFilename", { fg = c.fg, bg = c.bg })
  hl("MiniStatuslineInactive", { fg = c.fg_dim, bg = c.bg })
  hl("MiniStatuslineModeCommand", { fg = c.bg, bg = c.accent })
  hl("MiniStatuslineModeInsert", { fg = c.bg, bg = c.accent })
  hl("MiniStatuslineModeNormal", { fg = c.bg, bg = c.fg_muted })
  hl("MiniStatuslineModeOther", { fg = c.bg, bg = c.fg_dim })
  hl("MiniStatuslineModeReplace", { fg = c.bg, bg = c.fg_muted })
  hl("MiniStatuslineModeVisual", { fg = c.bg, bg = c.accent })

  hl("TelescopeNormal", { fg = c.fg, bg = c.bg })
  hl("TelescopeBorder", { fg = c.border, bg = c.bg })
  hl("TelescopeTitle", { fg = c.accent, bg = c.bg })
  hl("TelescopePromptNormal", { fg = c.fg, bg = c.bg })
  hl("TelescopePromptBorder", { fg = c.border, bg = c.bg })
  hl("TelescopePromptTitle", { fg = c.accent, bg = c.bg })
  hl("TelescopePromptPrefix", { fg = c.accent, bg = c.bg })
  hl("TelescopeResultsNormal", { fg = c.fg, bg = c.bg })
  hl("TelescopeResultsBorder", { fg = c.border, bg = c.bg })
  hl("TelescopeResultsTitle", { fg = c.accent, bg = c.bg })
  hl("TelescopePreviewNormal", { fg = c.fg, bg = c.bg })
  hl("TelescopePreviewBorder", { fg = c.border, bg = c.bg })
  hl("TelescopePreviewTitle", { fg = c.accent, bg = c.bg })
  hl("TelescopeSelection", { fg = c.fg, bg = c.bg_selected })
  hl("TelescopeSelectionCaret", { fg = c.accent, bg = c.bg_selected })
  hl("TelescopeMatching", { fg = c.accent })

  hl("BlinkCmpMenu", { fg = c.fg, bg = c.bg_elevated })
  hl("BlinkCmpMenuBorder", { fg = c.border, bg = c.bg_elevated })
  hl("BlinkCmpMenuSelection", { bg = c.bg_selected })
  hl("BlinkCmpLabel", { fg = c.fg })
  hl("BlinkCmpLabelMatch", { fg = c.accent })
  hl("BlinkCmpLabelDescription", { fg = c.fg_muted })
  hl("BlinkCmpKind", { fg = c.accent })
  hl("BlinkCmpDoc", { fg = c.fg, bg = c.bg_elevated })
  hl("BlinkCmpDocBorder", { fg = c.border, bg = c.bg_elevated })
  hl("BlinkCmpSignatureHelp", { fg = c.fg, bg = c.bg_elevated })
  hl("BlinkCmpSignatureHelpBorder", { fg = c.border, bg = c.bg_elevated })

  hl("OilDir", { fg = c.accent })
  hl("OilFile", { fg = c.fg })
  hl("OilSocket", { fg = c.fg_muted })
  hl("OilLink", { fg = c.string })
  hl("OilLinkTarget", { fg = c.fg_muted })

  hl("@variable", { fg = c.fg })
  hl("@variable.builtin", { fg = c.keyword })
  hl("@variable.parameter", { fg = c.fg })
  hl("@variable.member", { fg = c.fg })
  hl("@constant", { fg = c.accent })
  hl("@constant.builtin", { fg = c.accent })
  hl("@constant.macro", { fg = c.accent })
  hl("@module", { fg = c.fg })
  hl("@label", { fg = c.accent })
  hl("@string", { fg = c.string })
  hl("@string.escape", { fg = c.accent })
  hl("@string.regexp", { fg = c.string })
  hl("@string.special", { fg = c.string })
  hl("@character", { fg = c.char or c.string })
  hl("@character.special", { fg = c.accent })
  hl("@boolean", { fg = c.accent })
  hl("@number", { fg = c.number or c.accent })
  hl("@number.float", { fg = c.number or c.accent })
  hl("@type", { fg = c.accent })
  hl("@type.builtin", { fg = c.accent })
  hl("@type.definition", { fg = c.accent })
  hl("@attribute", { fg = c.keyword })
  hl("@property", { fg = c.fg })
  hl("@function", { fg = c.accent })
  hl("@function.builtin", { fg = c.accent })
  hl("@function.macro", { fg = c.accent })
  hl("@function.method", { fg = c.accent })
  hl("@constructor", { fg = c.accent })
  hl("@operator", { fg = c.keyword })
  hl("@keyword", { fg = c.keyword })
  hl("@keyword.modifier", { fg = c.keyword })
  hl("@keyword.type", { fg = c.keyword })
  hl("@keyword.coroutine", { fg = c.keyword })
  hl("@keyword.function", { fg = c.keyword })
  hl("@keyword.operator", { fg = c.keyword })
  hl("@keyword.import", { fg = c.keyword })
  hl("@keyword.repeat", { fg = c.keyword })
  hl("@keyword.return", { fg = c.keyword })
  hl("@keyword.exception", { fg = c.keyword })
  hl("@keyword.conditional", { fg = c.keyword })
  hl("@punctuation", { fg = c.fg_muted })
  hl("@punctuation.delimiter", { fg = c.fg_muted })
  hl("@punctuation.bracket", { fg = c.fg_muted })
  hl("@punctuation.special", { fg = c.fg_muted })
  hl("@comment", { fg = c.comment })
  hl("@comment.documentation", { fg = c.comment })
  hl("@comment.error", { fg = c.error or c.fg })
  hl("@comment.warning", { fg = c.warning or c.accent })
  hl("@comment.todo", { fg = c.accent })
  hl("@comment.note", { fg = c.info or c.accent })
  hl("@markup.heading", { fg = c.accent })
  hl("@markup.quote", { fg = c.fg_muted })
  hl("@markup.math", { fg = c.accent })
  hl("@markup.link", { fg = c.accent })
  hl("@markup.link.label", { fg = c.accent })
  hl("@markup.link.url", { fg = c.string, underline = true })
  hl("@markup.raw", { fg = c.string })
  hl("@markup.list", { fg = c.fg_muted })
  hl("@markup.strong", { bold = true })
  hl("@markup.italic", { italic = true })
  hl("@markup.strikethrough", { strikethrough = true })
  hl("@tag", { fg = c.accent })
  hl("@tag.attribute", { fg = c.fg_muted })
  hl("@tag.delimiter", { fg = c.fg_muted })

  hl("FlashLabel", { fg = c.bg, bg = c.accent, bold = true })
  hl("FlashMatch", { fg = c.accent })
  hl("FlashCurrent", { fg = c.bg, bg = c.string })
  hl("FlashBackdrop", { fg = c.comment })

  -- Core UI enhancements
  hl("NormalNC", { fg = c.fg_muted, bg = c.bg })
  hl("WinBar", { fg = c.fg, bg = c.bg })
  hl("WinBarNC", { fg = c.fg_muted, bg = c.bg })
  hl("Conceal", { fg = c.fg_dim })
  hl("SpellBad", { sp = c.error or c.accent, undercurl = true })
  hl("SpellCap", { sp = c.warning or c.accent, undercurl = true })
  hl("SpellLocal", { sp = c.info or c.accent, undercurl = true })
  hl("SpellRare", { sp = c.hint or c.accent, undercurl = true })
  hl("ColorColumn", { bg = c.bg_elevated })
  hl("QuickFixLine", { bg = c.bg_selected })

  -- nvim-cmp
  hl("CmpItemAbbr", { fg = c.fg })
  hl("CmpItemAbbrDeprecated", { fg = c.fg_dim, strikethrough = true })
  hl("CmpItemAbbrMatch", { fg = c.accent })
  hl("CmpItemAbbrMatchFuzzy", { fg = c.accent })
  hl("CmpItemKind", { fg = c.accent })
  hl("CmpItemMenu", { fg = c.fg_muted })
  hl("CmpItemKindText", { fg = c.fg })
  hl("CmpItemKindMethod", { fg = c.accent })
  hl("CmpItemKindFunction", { fg = c.accent })
  hl("CmpItemKindConstructor", { fg = c.accent })
  hl("CmpItemKindField", { fg = c.fg })
  hl("CmpItemKindVariable", { fg = c.fg })
  hl("CmpItemKindClass", { fg = c.accent })
  hl("CmpItemKindInterface", { fg = c.accent })
  hl("CmpItemKindModule", { fg = c.keyword })
  hl("CmpItemKindProperty", { fg = c.fg })
  hl("CmpItemKindUnit", { fg = c.number or c.accent })
  hl("CmpItemKindValue", { fg = c.string })
  hl("CmpItemKindEnum", { fg = c.accent })
  hl("CmpItemKindKeyword", { fg = c.keyword })
  hl("CmpItemKindSnippet", { fg = c.string })
  hl("CmpItemKindColor", { fg = c.accent })
  hl("CmpItemKindFile", { fg = c.fg })
  hl("CmpItemKindReference", { fg = c.accent })
  hl("CmpItemKindFolder", { fg = c.accent })
  hl("CmpItemKindEnumMember", { fg = c.accent })
  hl("CmpItemKindConstant", { fg = c.constant or c.accent })
  hl("CmpItemKindStruct", { fg = c.accent })
  hl("CmpItemKindEvent", { fg = c.accent })
  hl("CmpItemKindOperator", { fg = c.keyword })
  hl("CmpItemKindTypeParameter", { fg = c.accent })

  -- nvim-tree
  hl("NvimTreeNormal", { fg = c.fg, bg = c.bg })
  hl("NvimTreeNormalNC", { fg = c.fg_muted, bg = c.bg })
  hl("NvimTreeRootFolder", { fg = c.accent, bold = true })
  hl("NvimTreeFolderName", { fg = c.accent })
  hl("NvimTreeFolderIcon", { fg = c.accent })
  hl("NvimTreeEmptyFolderName", { fg = c.fg_muted })
  hl("NvimTreeOpenedFolderName", { fg = c.accent })
  hl("NvimTreeSymlink", { fg = c.string })
  hl("NvimTreeSpecialFile", { fg = c.accent })
  hl("NvimTreeImageFile", { fg = c.fg })
  hl("NvimTreeIndentMarker", { fg = c.fg_dim })
  hl("NvimTreeGitDirty", { fg = c.changed })
  hl("NvimTreeGitStaged", { fg = c.added })
  hl("NvimTreeGitMerge", { fg = c.changed })
  hl("NvimTreeGitRenamed", { fg = c.changed })
  hl("NvimTreeGitNew", { fg = c.added })
  hl("NvimTreeGitDeleted", { fg = c.deleted })

  -- neo-tree
  hl("NeoTreeNormal", { fg = c.fg, bg = c.bg })
  hl("NeoTreeNormalNC", { fg = c.fg_muted, bg = c.bg })
  hl("NeoTreeDirectoryName", { fg = c.accent })
  hl("NeoTreeDirectoryIcon", { fg = c.accent })
  hl("NeoTreeRootName", { fg = c.accent, bold = true })
  hl("NeoTreeFileName", { fg = c.fg })
  hl("NeoTreeFileIcon", { fg = c.fg })
  hl("NeoTreeSymbolicLinkTarget", { fg = c.string })
  hl("NeoTreeIndentMarker", { fg = c.fg_dim })
  hl("NeoTreeGitAdded", { fg = c.added })
  hl("NeoTreeGitConflict", { fg = c.error or c.accent })
  hl("NeoTreeGitDeleted", { fg = c.deleted })
  hl("NeoTreeGitIgnored", { fg = c.fg_dim })
  hl("NeoTreeGitModified", { fg = c.changed })
  hl("NeoTreeGitUntracked", { fg = c.added })
  hl("NeoTreeTitleBar", { fg = c.bg, bg = c.accent })
  hl("NeoTreeFloatBorder", { fg = c.border, bg = c.bg })
  hl("NeoTreeFloatTitle", { fg = c.accent, bg = c.bg })

  -- indent-blankline
  hl("IblIndent", { fg = c.fg_dim })
  hl("IblScope", { fg = c.accent })
  hl("IndentBlanklineChar", { fg = c.fg_dim })
  hl("IndentBlanklineContextChar", { fg = c.accent })

  -- nvim-notify
  hl("NotifyERRORBorder", { fg = c.error or c.accent })
  hl("NotifyERRORIcon", { fg = c.error or c.accent })
  hl("NotifyERRORTitle", { fg = c.error or c.accent })
  hl("NotifyWARNBorder", { fg = c.warning or c.accent })
  hl("NotifyWARNIcon", { fg = c.warning or c.accent })
  hl("NotifyWARNTitle", { fg = c.warning or c.accent })
  hl("NotifyINFOBorder", { fg = c.info or c.accent })
  hl("NotifyINFOIcon", { fg = c.info or c.accent })
  hl("NotifyINFOTitle", { fg = c.info or c.accent })
  hl("NotifyDEBUGBorder", { fg = c.fg_muted })
  hl("NotifyDEBUGIcon", { fg = c.fg_muted })
  hl("NotifyDEBUGTitle", { fg = c.fg_muted })
  hl("NotifyTRACEBorder", { fg = c.hint or c.accent })
  hl("NotifyTRACEIcon", { fg = c.hint or c.accent })
  hl("NotifyTRACETitle", { fg = c.hint or c.accent })
  hl("NotifyBackground", { bg = c.bg })

  -- noice.nvim
  hl("NoiceCmdline", { fg = c.fg })
  hl("NoiceCmdlineIcon", { fg = c.accent })
  hl("NoiceCmdlineIconSearch", { fg = c.accent })
  hl("NoiceCmdlinePopup", { fg = c.fg, bg = c.bg_elevated })
  hl("NoiceCmdlinePopupBorder", { fg = c.border })
  hl("NoiceConfirm", { fg = c.fg, bg = c.bg_elevated })
  hl("NoiceConfirmBorder", { fg = c.border })
  hl("NoicePopup", { fg = c.fg, bg = c.bg_elevated })
  hl("NoicePopupBorder", { fg = c.border })
  hl("NoicePopupmenu", { fg = c.fg, bg = c.bg_elevated })
  hl("NoicePopupmenuBorder", { fg = c.border })
  hl("NoicePopupmenuSelected", { bg = c.bg_selected })
  hl("NoiceScrollbar", { bg = c.bg_elevated })
  hl("NoiceScrollbarThumb", { bg = c.fg_dim })
  hl("NoiceMini", { fg = c.fg, bg = c.bg })
  hl("NoiceVirtualText", { fg = c.accent })

  -- which-key
  hl("WhichKey", { fg = c.accent })
  hl("WhichKeyGroup", { fg = c.keyword })
  hl("WhichKeySeparator", { fg = c.fg_dim })
  hl("WhichKeyDesc", { fg = c.fg })
  hl("WhichKeyFloat", { bg = c.bg_elevated })
  hl("WhichKeyBorder", { fg = c.border })
  hl("WhichKeyValue", { fg = c.fg_muted })

  -- hop.nvim
  hl("HopNextKey", { fg = c.bg, bg = c.accent, bold = true })
  hl("HopNextKey1", { fg = c.bg, bg = c.accent, bold = true })
  hl("HopNextKey2", { fg = c.accent })
  hl("HopUnmatched", { fg = c.comment })

  -- leap.nvim
  hl("LeapMatch", { fg = c.accent, bold = true })
  hl("LeapLabelPrimary", { fg = c.bg, bg = c.accent, bold = true })
  hl("LeapLabelSecondary", { fg = c.bg, bg = c.string, bold = true })
  hl("LeapBackdrop", { fg = c.comment })

  -- lightspeed.nvim
  hl("LightspeedLabel", { fg = c.bg, bg = c.accent, bold = true })
  hl("LightspeedLabelOverlapped", { fg = c.bg, bg = c.string, bold = true })
  hl("LightspeedLabelDistant", { fg = c.bg, bg = c.keyword, bold = true })
  hl("LightspeedShortcut", { fg = c.bg, bg = c.accent, bold = true })
  hl("LightspeedMaskedChar", { fg = c.fg_dim })
  hl("LightspeedUnlabeledMatch", { fg = c.accent, bold = true })
  hl("LightspeedGreyWash", { fg = c.comment })

  -- sneak
  hl("Sneak", { fg = c.bg, bg = c.accent })
  hl("SneakLabel", { fg = c.bg, bg = c.accent, bold = true })
  hl("SneakScope", { bg = c.bg_hover })

  -- neogit
  hl("NeogitBranch", { fg = c.accent })
  hl("NeogitRemote", { fg = c.string })
  hl("NeogitHunkHeader", { fg = c.fg, bg = c.bg_elevated })
  hl("NeogitHunkHeaderHighlight", { fg = c.fg, bg = c.bg_hover })
  hl("NeogitDiffContextHighlight", { bg = c.bg_elevated })
  hl("NeogitDiffDeleteHighlight", { fg = c.deleted, bg = c.bg_diff_delete or c.bg })
  hl("NeogitDiffAddHighlight", { fg = c.added, bg = c.bg_diff_add or c.bg })
  hl("NeogitNotificationInfo", { fg = c.info or c.accent })
  hl("NeogitNotificationWarning", { fg = c.warning or c.accent })
  hl("NeogitNotificationError", { fg = c.error or c.accent })

  -- lazy.nvim
  hl("LazyH1", { fg = c.bg, bg = c.accent })
  hl("LazyH2", { fg = c.accent, bold = true })
  hl("LazyButton", { fg = c.fg, bg = c.bg_elevated })
  hl("LazyButtonActive", { fg = c.bg, bg = c.accent })
  hl("LazyComment", { fg = c.comment })
  hl("LazyCommit", { fg = c.fg_muted })
  hl("LazyCommitIssue", { fg = c.accent })
  hl("LazyCommitType", { fg = c.keyword })
  hl("LazyDimmed", { fg = c.fg_dim })
  hl("LazyDir", { fg = c.accent })
  hl("LazyNormal", { fg = c.fg, bg = c.bg })
  hl("LazyProgressDone", { fg = c.accent })
  hl("LazyProgressTodo", { fg = c.fg_dim })
  hl("LazyReasonCmd", { fg = c.accent })
  hl("LazyReasonEvent", { fg = c.string })
  hl("LazyReasonFt", { fg = c.keyword })
  hl("LazyReasonImport", { fg = c.fg })
  hl("LazyReasonKeys", { fg = c.accent })
  hl("LazyReasonPlugin", { fg = c.accent })
  hl("LazyReasonSource", { fg = c.fg_muted })
  hl("LazyReasonStart", { fg = c.string })
  hl("LazySpecial", { fg = c.accent })
  hl("LazyTaskOutput", { fg = c.fg })
  hl("LazyUrl", { fg = c.string, underline = true })
  hl("LazyValue", { fg = c.string })

  -- rainbow-delimiters
  hl("RainbowDelimiterRed", { fg = c.accent })
  hl("RainbowDelimiterYellow", { fg = c.warning or c.accent })
  hl("RainbowDelimiterBlue", { fg = c.info or c.accent })
  hl("RainbowDelimiterOrange", { fg = c.number or c.accent })
  hl("RainbowDelimiterGreen", { fg = c.string })
  hl("RainbowDelimiterViolet", { fg = c.keyword })
  hl("RainbowDelimiterCyan", { fg = c.hint or c.accent })

  -- render-markdown
  hl("RenderMarkdownH1", { fg = c.accent, bold = true })
  hl("RenderMarkdownH2", { fg = c.accent, bold = true })
  hl("RenderMarkdownH3", { fg = c.accent, bold = true })
  hl("RenderMarkdownH4", { fg = c.accent })
  hl("RenderMarkdownH5", { fg = c.accent })
  hl("RenderMarkdownH6", { fg = c.accent })
  hl("RenderMarkdownH1Bg", { bg = c.bg_elevated })
  hl("RenderMarkdownH2Bg", { bg = c.bg_elevated })
  hl("RenderMarkdownH3Bg", { bg = c.bg_elevated })
  hl("RenderMarkdownCode", { bg = c.bg_elevated })
  hl("RenderMarkdownCodeInline", { bg = c.bg_elevated })
  hl("RenderMarkdownBullet", { fg = c.accent })
  hl("RenderMarkdownQuote", { fg = c.fg_muted })
  hl("RenderMarkdownLink", { fg = c.accent, underline = true })
  hl("RenderMarkdownMath", { fg = c.accent })
  hl("RenderMarkdownChecked", { fg = c.added })
  hl("RenderMarkdownUnchecked", { fg = c.fg_muted })
  hl("RenderMarkdownTableHead", { fg = c.accent })
  hl("RenderMarkdownTableRow", { fg = c.fg })
  hl("RenderMarkdownDash", { fg = c.fg_dim })

  -- headlines.nvim
  hl("Headline1", { bg = c.bg_elevated })
  hl("Headline2", { bg = c.bg_elevated })
  hl("Headline3", { bg = c.bg_elevated })
  hl("Headline4", { bg = c.bg_elevated })
  hl("Headline5", { bg = c.bg_elevated })
  hl("Headline6", { bg = c.bg_elevated })
  hl("CodeBlock", { bg = c.bg_elevated })
  hl("Dash", { fg = c.fg_dim })
  hl("Quote", { fg = c.fg_muted })

  -- todo-comments.nvim
  hl("TodoBgFIX", { fg = c.bg, bg = c.error or c.accent, bold = true })
  hl("TodoBgHACK", { fg = c.bg, bg = c.warning or c.accent, bold = true })
  hl("TodoBgNOTE", { fg = c.bg, bg = c.hint or c.accent, bold = true })
  hl("TodoBgPERF", { fg = c.bg, bg = c.keyword, bold = true })
  hl("TodoBgTODO", { fg = c.bg, bg = c.info or c.accent, bold = true })
  hl("TodoBgWARN", { fg = c.bg, bg = c.warning or c.accent, bold = true })
  hl("TodoFgFIX", { fg = c.error or c.accent })
  hl("TodoFgHACK", { fg = c.warning or c.accent })
  hl("TodoFgNOTE", { fg = c.hint or c.accent })
  hl("TodoFgPERF", { fg = c.keyword })
  hl("TodoFgTODO", { fg = c.info or c.accent })
  hl("TodoFgWARN", { fg = c.warning or c.accent })
  hl("TodoSignFIX", { fg = c.error or c.accent })
  hl("TodoSignHACK", { fg = c.warning or c.accent })
  hl("TodoSignNOTE", { fg = c.hint or c.accent })
  hl("TodoSignPERF", { fg = c.keyword })
  hl("TodoSignTODO", { fg = c.info or c.accent })
  hl("TodoSignWARN", { fg = c.warning or c.accent })

  -- trouble.nvim
  hl("TroubleNormal", { fg = c.fg, bg = c.bg })
  hl("TroubleNormalNC", { fg = c.fg_muted, bg = c.bg })
  hl("TroubleText", { fg = c.fg })
  hl("TroubleCount", { fg = c.accent, bg = c.bg_elevated })
  hl("TroubleFile", { fg = c.accent })
  hl("TroubleFoldIcon", { fg = c.fg_muted })
  hl("TroubleLocation", { fg = c.fg_muted })
  hl("TroublePreview", { bg = c.bg_hover })
  hl("TroubleSource", { fg = c.fg_dim })
  hl("TroubleSignError", { fg = c.error or c.accent })
  hl("TroubleSignWarning", { fg = c.warning or c.accent })
  hl("TroubleSignInformation", { fg = c.info or c.accent })
  hl("TroubleSignHint", { fg = c.hint or c.accent })

  -- LSP semantic tokens
  hl("@lsp.type.class", { fg = c.accent })
  hl("@lsp.type.decorator", { fg = c.accent })
  hl("@lsp.type.enum", { fg = c.accent })
  hl("@lsp.type.enumMember", { fg = c.constant or c.accent })
  hl("@lsp.type.function", { fg = c.accent })
  hl("@lsp.type.interface", { fg = c.accent })
  hl("@lsp.type.macro", { fg = c.accent })
  hl("@lsp.type.method", { fg = c.accent })
  hl("@lsp.type.namespace", { fg = c.fg })
  hl("@lsp.type.parameter", { fg = c.fg })
  hl("@lsp.type.property", { fg = c.fg })
  hl("@lsp.type.struct", { fg = c.accent })
  hl("@lsp.type.type", { fg = c.accent })
  hl("@lsp.type.typeParameter", { fg = c.accent })
  hl("@lsp.type.variable", { fg = c.fg })
  hl("@lsp.mod.deprecated", { strikethrough = true })
  hl("@lsp.mod.readonly", { fg = c.constant or c.accent })
  hl("@lsp.mod.defaultLibrary", { fg = c.accent })
  hl("@lsp.typemod.function.defaultLibrary", { fg = c.accent })
  hl("@lsp.typemod.variable.defaultLibrary", { fg = c.accent })

  -- gitsigns additional groups
  hl("GitSignsAddLn", { bg = c.bg_diff_add or c.bg })
  hl("GitSignsChangeLn", { bg = c.bg_hover })
  hl("GitSignsDeleteLn", { bg = c.bg_diff_delete or c.bg })
  hl("GitSignsCurrentLineBlame", { fg = c.fg_dim })
  hl("GitSignsAddInline", { bg = c.bg_diff_add or c.bg_hover })
  hl("GitSignsChangeInline", { bg = c.bg_hover })
  hl("GitSignsDeleteInline", { bg = c.bg_diff_delete or c.bg_hover })

  -- aerial.nvim
  hl("AerialLine", { bg = c.bg_selected })
  hl("AerialGuide", { fg = c.fg_dim })
  hl("AerialClass", { fg = c.accent })
  hl("AerialClassIcon", { fg = c.accent })
  hl("AerialFunction", { fg = c.accent })
  hl("AerialFunctionIcon", { fg = c.accent })
  hl("AerialMethod", { fg = c.accent })
  hl("AerialMethodIcon", { fg = c.accent })

  -- navic
  hl("NavicText", { fg = c.fg })
  hl("NavicSeparator", { fg = c.fg_dim })
  hl("NavicIconsFile", { fg = c.fg })
  hl("NavicIconsModule", { fg = c.keyword })
  hl("NavicIconsNamespace", { fg = c.fg })
  hl("NavicIconsPackage", { fg = c.keyword })
  hl("NavicIconsClass", { fg = c.accent })
  hl("NavicIconsMethod", { fg = c.accent })
  hl("NavicIconsProperty", { fg = c.fg })
  hl("NavicIconsField", { fg = c.fg })
  hl("NavicIconsConstructor", { fg = c.accent })
  hl("NavicIconsEnum", { fg = c.accent })
  hl("NavicIconsInterface", { fg = c.accent })
  hl("NavicIconsFunction", { fg = c.accent })
  hl("NavicIconsVariable", { fg = c.fg })
  hl("NavicIconsConstant", { fg = c.constant or c.accent })
  hl("NavicIconsString", { fg = c.string })
  hl("NavicIconsNumber", { fg = c.number or c.accent })
  hl("NavicIconsBoolean", { fg = c.accent })
  hl("NavicIconsArray", { fg = c.accent })
  hl("NavicIconsObject", { fg = c.accent })
  hl("NavicIconsKey", { fg = c.keyword })
  hl("NavicIconsNull", { fg = c.fg_dim })
  hl("NavicIconsEnumMember", { fg = c.accent })
  hl("NavicIconsStruct", { fg = c.accent })
  hl("NavicIconsEvent", { fg = c.accent })
  hl("NavicIconsOperator", { fg = c.keyword })
  hl("NavicIconsTypeParameter", { fg = c.accent })

  -- fzf-lua
  hl("FzfLuaNormal", { fg = c.fg, bg = c.bg })
  hl("FzfLuaBorder", { fg = c.border, bg = c.bg })
  hl("FzfLuaTitle", { fg = c.accent })
  hl("FzfLuaPreviewNormal", { fg = c.fg, bg = c.bg })
  hl("FzfLuaPreviewBorder", { fg = c.border, bg = c.bg })
  hl("FzfLuaPreviewTitle", { fg = c.accent })
  hl("FzfLuaCursor", { fg = c.bg, bg = c.accent })
  hl("FzfLuaCursorLine", { bg = c.bg_selected })
  hl("FzfLuaSearch", { fg = c.accent })

  -- scrollbar.nvim
  hl("ScrollbarHandle", { bg = c.bg_hover })
  hl("ScrollbarSearchHandle", { fg = c.accent, bg = c.bg_hover })
  hl("ScrollbarSearch", { fg = c.accent })
  hl("ScrollbarErrorHandle", { fg = c.error or c.accent, bg = c.bg_hover })
  hl("ScrollbarError", { fg = c.error or c.accent })
  hl("ScrollbarWarnHandle", { fg = c.warning or c.accent, bg = c.bg_hover })
  hl("ScrollbarWarn", { fg = c.warning or c.accent })
  hl("ScrollbarInfoHandle", { fg = c.info or c.accent, bg = c.bg_hover })
  hl("ScrollbarInfo", { fg = c.info or c.accent })
  hl("ScrollbarHintHandle", { fg = c.hint or c.accent, bg = c.bg_hover })
  hl("ScrollbarHint", { fg = c.hint or c.accent })
  hl("ScrollbarMiscHandle", { fg = c.fg_muted, bg = c.bg_hover })
  hl("ScrollbarMisc", { fg = c.fg_muted })

  -- bufferline.nvim
  hl("BufferLineFill", { bg = c.bg })
  hl("BufferLineBackground", { fg = c.fg_muted, bg = c.bg })
  hl("BufferLineBuffer", { fg = c.fg_muted, bg = c.bg })
  hl("BufferLineBufferSelected", { fg = c.fg, bg = c.bg_elevated })
  hl("BufferLineBufferVisible", { fg = c.fg_muted, bg = c.bg })
  hl("BufferLineTab", { fg = c.fg_muted, bg = c.bg })
  hl("BufferLineTabSelected", { fg = c.fg, bg = c.bg_elevated })
  hl("BufferLineTabClose", { fg = c.fg_muted, bg = c.bg })
  hl("BufferLineIndicatorSelected", { fg = c.accent, bg = c.bg_elevated })
  hl("BufferLineSeparator", { fg = c.border, bg = c.bg })
  hl("BufferLineSeparatorSelected", { fg = c.border, bg = c.bg_elevated })
  hl("BufferLineModified", { fg = c.changed })
  hl("BufferLineModifiedSelected", { fg = c.changed })
  hl("BufferLineModifiedVisible", { fg = c.changed })

  -- mini.icons
  hl("MiniIconsAzure", { fg = c.info or c.accent })
  hl("MiniIconsBlue", { fg = c.info or c.accent })
  hl("MiniIconsCyan", { fg = c.hint or c.accent })
  hl("MiniIconsGreen", { fg = c.added })
  hl("MiniIconsGrey", { fg = c.fg_muted })
  hl("MiniIconsOrange", { fg = c.warning or c.accent })
  hl("MiniIconsPurple", { fg = c.keyword })
  hl("MiniIconsRed", { fg = c.error or c.accent })
  hl("MiniIconsYellow", { fg = c.warning or c.accent })

  -- mini.files
  hl("MiniFilesNormal", { fg = c.fg, bg = c.bg })
  hl("MiniFilesBorder", { fg = c.border, bg = c.bg })
  hl("MiniFilesTitle", { fg = c.accent, bg = c.bg })
  hl("MiniFilesTitleFocused", { fg = c.accent, bg = c.bg, bold = true })
  hl("MiniFilesCursorLine", { bg = c.bg_selected })
  hl("MiniFilesDirectory", { fg = c.accent })
  hl("MiniFilesFile", { fg = c.fg })

  -- mini.pick
  hl("MiniPickNormal", { fg = c.fg, bg = c.bg })
  hl("MiniPickBorder", { fg = c.border, bg = c.bg })
  hl("MiniPickBorderBusy", { fg = c.warning or c.accent, bg = c.bg })
  hl("MiniPickBorderText", { fg = c.accent, bg = c.bg })
  hl("MiniPickPrompt", { fg = c.accent })
  hl("MiniPickMatchCurrent", { bg = c.bg_selected })
  hl("MiniPickMatchMarked", { fg = c.accent, bg = c.bg_hover })
  hl("MiniPickMatchRanges", { fg = c.accent })
  hl("MiniPickPreviewLine", { bg = c.bg_hover })
  hl("MiniPickPreviewRegion", { bg = c.bg_selected })

  -- mini.indentscope
  hl("MiniIndentscopeSymbol", { fg = c.accent })
  hl("MiniIndentscopeSymbolOff", { fg = c.fg_dim })

  -- mini.jump
  hl("MiniJump", { fg = c.bg, bg = c.accent })
  hl("MiniJump2dSpot", { fg = c.bg, bg = c.accent, bold = true })
  hl("MiniJump2dSpotAhead", { fg = c.bg, bg = c.string })
  hl("MiniJump2dSpotUnique", { fg = c.bg, bg = c.accent, bold = true })
  hl("MiniJump2dDim", { fg = c.comment })

  -- mini.hipatterns
  hl("MiniHipatternsFixme", { fg = c.bg, bg = c.error or c.accent, bold = true })
  hl("MiniHipatternsHack", { fg = c.bg, bg = c.warning or c.accent, bold = true })
  hl("MiniHipatternsNote", { fg = c.bg, bg = c.hint or c.accent, bold = true })
  hl("MiniHipatternsTodo", { fg = c.bg, bg = c.info or c.accent, bold = true })

  -- mini.surround
  hl("MiniSurround", { fg = c.bg, bg = c.accent })

  -- mini.cursorword
  hl("MiniCursorword", { bg = c.bg_hover })
  hl("MiniCursorwordCurrent", { bg = c.bg_hover })

  -- mini.trailspace
  hl("MiniTrailspace", { bg = c.error or c.accent })

  -- mini.notify
  hl("MiniNotifyBorder", { fg = c.border })
  hl("MiniNotifyNormal", { fg = c.fg, bg = c.bg_elevated })
  hl("MiniNotifyTitle", { fg = c.accent })

  -- yanky.nvim
  hl("YankyYanked", { bg = c.bg_hover })
  hl("YankyPut", { bg = c.bg_hover })
end

return M
