local M = {}

function M.apply(c)
  local hl = function(group, opts)
    vim.api.nvim_set_hl(0, group, opts)
  end

  hl("Normal", { fg = c.fg, bg = c.bg })
  hl("NormalFloat", { fg = c.fg, bg = c.bg_elevated })
  hl("FloatBorder", { fg = c.border, bg = c.bg_elevated })
  hl("FloatTitle", { fg = c.accent, bg = c.bg_elevated })
  hl("Cursor", { fg = c.bg, bg = c.accent })
  hl("CursorLine", { bg = c.bg_hover })
  hl("CursorLineNr", { fg = c.line_nr_active })
  hl("LineNr", { fg = c.line_nr })
  hl("SignColumn", { bg = c.bg })
  hl("VertSplit", { fg = c.border })
  hl("WinSeparator", { fg = c.border })
  hl("StatusLine", { fg = c.fg_muted, bg = c.bg })
  hl("StatusLineNC", { fg = c.fg_dim, bg = c.bg })
  hl("TabLine", { fg = c.fg_muted, bg = c.bg })
  hl("TabLineFill", { bg = c.bg })
  hl("TabLineSel", { fg = c.fg, bg = c.bg_elevated })
  hl("Pmenu", { fg = c.fg, bg = c.bg_elevated })
  hl("PmenuSel", { fg = c.fg, bg = c.bg_selected })
  hl("PmenuSbar", { bg = c.bg_elevated })
  hl("PmenuThumb", { bg = c.bg_hover })
  hl("Visual", { bg = c.bg_hover })
  hl("Search", { fg = c.fg, bg = c.search })
  hl("IncSearch", { fg = c.bg, bg = c.accent })
  hl("CurSearch", { fg = c.bg, bg = c.accent })
  hl("MatchParen", { fg = c.accent, bg = c.bg_hover })
  hl("Folded", { fg = c.fg_muted, bg = c.bg_elevated })
  hl("FoldColumn", { fg = c.fg_dim, bg = c.bg })
  hl("NonText", { fg = c.fg_dim })
  hl("SpecialKey", { fg = c.fg_dim })
  hl("Whitespace", { fg = c.fg_dim })
  hl("EndOfBuffer", { fg = c.bg })
  hl("Directory", { fg = c.accent })
  hl("Question", { fg = c.accent })
  hl("MoreMsg", { fg = c.accent })
  hl("ModeMsg", { fg = c.fg_muted })
  hl("ErrorMsg", { fg = c.error or c.fg })
  hl("WarningMsg", { fg = c.warning or c.accent })
  hl("Title", { fg = c.accent })
  hl("WildMenu", { fg = c.fg, bg = c.bg_selected })

  hl("Comment", { fg = c.comment })
  hl("Constant", { fg = c.constant or c.accent })
  hl("String", { fg = c.string })
  hl("Character", { fg = c.char or c.string })
  hl("Number", { fg = c.number or c.accent })
  hl("Boolean", { fg = c.accent })
  hl("Float", { fg = c.number or c.accent })
  hl("Identifier", { fg = c.fg })
  hl("Function", { fg = c.accent })
  hl("Statement", { fg = c.keyword })
  hl("Conditional", { fg = c.keyword })
  hl("Repeat", { fg = c.keyword })
  hl("Label", { fg = c.accent })
  hl("Operator", { fg = c.keyword })
  hl("Keyword", { fg = c.keyword })
  hl("Exception", { fg = c.keyword })
  hl("PreProc", { fg = c.keyword })
  hl("Include", { fg = c.keyword })
  hl("Define", { fg = c.keyword })
  hl("Macro", { fg = c.accent })
  hl("PreCondit", { fg = c.keyword })
  hl("Type", { fg = c.accent })
  hl("StorageClass", { fg = c.keyword })
  hl("Structure", { fg = c.accent })
  hl("Typedef", { fg = c.accent })
  hl("Special", { fg = c.accent })
  hl("SpecialChar", { fg = c.accent })
  hl("Tag", { fg = c.accent })
  hl("Delimiter", { fg = c.fg_muted })
  hl("SpecialComment", { fg = c.comment })
  hl("Debug", { fg = c.error or c.fg })
  hl("Underlined", { fg = c.accent, underline = true })
  hl("Error", { fg = c.error or c.fg })
  hl("Todo", { fg = c.accent, bg = c.bg_elevated })

  if c.error then
    hl("DiagnosticError", { fg = c.error })
    hl("DiagnosticUnderlineError", { sp = c.error, undercurl = true })
    hl("DiagnosticVirtualTextError", { fg = c.error, bg = c.bg })
    hl("DiagnosticFloatingError", { fg = c.error })
    hl("DiagnosticSignError", { fg = c.error })
  end

  if c.warning then
    hl("DiagnosticWarn", { fg = c.warning })
    hl("DiagnosticUnderlineWarn", { sp = c.warning, undercurl = true })
    hl("DiagnosticVirtualTextWarn", { fg = c.warning, bg = c.bg })
    hl("DiagnosticFloatingWarn", { fg = c.warning })
    hl("DiagnosticSignWarn", { fg = c.warning })
  end

  if c.info then
    hl("DiagnosticInfo", { fg = c.info })
    hl("DiagnosticUnderlineInfo", { sp = c.info, undercurl = true })
    hl("DiagnosticVirtualTextInfo", { fg = c.info, bg = c.bg })
    hl("DiagnosticFloatingInfo", { fg = c.info })
    hl("DiagnosticSignInfo", { fg = c.info })
  end

  if c.hint then
    hl("DiagnosticHint", { fg = c.hint })
    hl("DiagnosticUnderlineHint", { sp = c.hint, undercurl = true })
    hl("DiagnosticVirtualTextHint", { fg = c.hint, bg = c.bg })
    hl("DiagnosticFloatingHint", { fg = c.hint })
    hl("DiagnosticSignHint", { fg = c.hint })
  end

  hl("LspReferenceText", { bg = c.bg_hover })
  hl("LspReferenceRead", { bg = c.bg_hover })
  hl("LspReferenceWrite", { bg = c.bg_hover })
  hl("LspSignatureActiveParameter", { fg = c.accent })
  hl("LspInlayHint", { fg = c.fg_dim, bg = c.bg })

  if c.bg_diff_add then
    hl("DiffAdd", { bg = c.bg_diff_add })
  elseif c.added then
    hl("DiffAdd", { fg = c.added, bg = c.bg })
  end

  if c.bg_diff_delete then
    hl("DiffDelete", { bg = c.bg_diff_delete })
  elseif c.deleted then
    hl("DiffDelete", { fg = c.deleted, bg = c.bg })
  end

  if c.changed then
    hl("DiffChange", { fg = c.changed, bg = c.bg })
    hl("DiffText", { fg = c.changed, bg = c.bg_hover })
  end

  if c.added then
    hl("Added", { fg = c.added })
    hl("GitSignsAdd", { fg = c.added })
    hl("MiniDiffSignAdd", { fg = c.added })
    hl("MiniDiffOverAdd", { fg = c.added, bg = c.bg })
  end

  if c.changed then
    hl("Changed", { fg = c.changed })
    hl("GitSignsChange", { fg = c.changed })
    hl("MiniDiffSignChange", { fg = c.changed })
    hl("MiniDiffOverChange", { fg = c.changed, bg = c.bg })
  end

  if c.deleted then
    hl("Removed", { fg = c.deleted })
    hl("GitSignsDelete", { fg = c.deleted })
    hl("MiniDiffSignDelete", { fg = c.deleted })
    hl("MiniDiffOverDelete", { fg = c.deleted, bg = c.bg })
  end

  hl("MiniStatuslineDevinfo", { fg = c.fg_muted, bg = c.bg })
  hl("MiniStatuslineFileinfo", { fg = c.fg_muted, bg = c.bg })
  hl("MiniStatuslineFilename", { fg = c.fg, bg = c.bg })
  hl("MiniStatuslineInactive", { fg = c.fg_dim, bg = c.bg })
  hl("MiniStatuslineModeCommand", { fg = c.bg, bg = c.accent })
  hl("MiniStatuslineModeInsert", { fg = c.bg, bg = c.accent })
  hl("MiniStatuslineModeNormal", { fg = c.bg, bg = c.fg_muted })
  hl("MiniStatuslineModeOther", { fg = c.bg, bg = c.fg_dim })
  hl("MiniStatuslineModeReplace", { fg = c.bg, bg = c.fg_muted })
  hl("MiniStatuslineModeVisual", { fg = c.bg, bg = c.accent })

  hl("TelescopeNormal", { fg = c.fg, bg = c.bg })
  hl("TelescopeBorder", { fg = c.border, bg = c.bg })
  hl("TelescopeTitle", { fg = c.accent, bg = c.bg })
  hl("TelescopePromptNormal", { fg = c.fg, bg = c.bg })
  hl("TelescopePromptBorder", { fg = c.border, bg = c.bg })
  hl("TelescopePromptTitle", { fg = c.accent, bg = c.bg })
  hl("TelescopePromptPrefix", { fg = c.accent, bg = c.bg })
  hl("TelescopeResultsNormal", { fg = c.fg, bg = c.bg })
  hl("TelescopeResultsBorder", { fg = c.border, bg = c.bg })
  hl("TelescopeResultsTitle", { fg = c.accent, bg = c.bg })
  hl("TelescopePreviewNormal", { fg = c.fg, bg = c.bg })
  hl("TelescopePreviewBorder", { fg = c.border, bg = c.bg })
  hl("TelescopePreviewTitle", { fg = c.accent, bg = c.bg })
  hl("TelescopeSelection", { fg = c.fg, bg = c.bg_selected })
  hl("TelescopeSelectionCaret", { fg = c.accent, bg = c.bg_selected })
  hl("TelescopeMatching", { fg = c.accent })

  hl("BlinkCmpMenu", { fg = c.fg, bg = c.bg_elevated })
  hl("BlinkCmpMenuBorder", { fg = c.border, bg = c.bg_elevated })
  hl("BlinkCmpMenuSelection", { bg = c.bg_selected })
  hl("BlinkCmpLabel", { fg = c.fg })
  hl("BlinkCmpLabelMatch", { fg = c.accent })
  hl("BlinkCmpLabelDescription", { fg = c.fg_muted })
  hl("BlinkCmpKind", { fg = c.accent })
  hl("BlinkCmpDoc", { fg = c.fg, bg = c.bg_elevated })
  hl("BlinkCmpDocBorder", { fg = c.border, bg = c.bg_elevated })
  hl("BlinkCmpSignatureHelp", { fg = c.fg, bg = c.bg_elevated })
  hl("BlinkCmpSignatureHelpBorder", { fg = c.border, bg = c.bg_elevated })

  hl("OilDir", { fg = c.accent })
  hl("OilFile", { fg = c.fg })
  hl("OilSocket", { fg = c.fg_muted })
  hl("OilLink", { fg = c.string })
  hl("OilLinkTarget", { fg = c.fg_muted })

  hl("@variable", { fg = c.fg })
  hl("@variable.builtin", { fg = c.keyword })
  hl("@variable.parameter", { fg = c.fg })
  hl("@variable.member", { fg = c.fg })
  hl("@constant", { fg = c.accent })
  hl("@constant.builtin", { fg = c.accent })
  hl("@constant.macro", { fg = c.accent })
  hl("@module", { fg = c.fg })
  hl("@label", { fg = c.accent })
  hl("@string", { fg = c.string })
  hl("@string.escape", { fg = c.accent })
  hl("@string.regexp", { fg = c.string })
  hl("@string.special", { fg = c.string })
  hl("@character", { fg = c.char or c.string })
  hl("@character.special", { fg = c.accent })
  hl("@boolean", { fg = c.accent })
  hl("@number", { fg = c.number or c.accent })
  hl("@number.float", { fg = c.number or c.accent })
  hl("@type", { fg = c.accent })
  hl("@type.builtin", { fg = c.accent })
  hl("@type.definition", { fg = c.accent })
  hl("@attribute", { fg = c.keyword })
  hl("@property", { fg = c.fg })
  hl("@function", { fg = c.accent })
  hl("@function.builtin", { fg = c.accent })
  hl("@function.macro", { fg = c.accent })
  hl("@function.method", { fg = c.accent })
  hl("@constructor", { fg = c.accent })
  hl("@operator", { fg = c.keyword })
  hl("@keyword", { fg = c.keyword })
  hl("@keyword.modifier", { fg = c.keyword })
  hl("@keyword.type", { fg = c.keyword })
  hl("@keyword.coroutine", { fg = c.keyword })
  hl("@keyword.function", { fg = c.keyword })
  hl("@keyword.operator", { fg = c.keyword })
  hl("@keyword.import", { fg = c.keyword })
  hl("@keyword.repeat", { fg = c.keyword })
  hl("@keyword.return", { fg = c.keyword })
  hl("@keyword.exception", { fg = c.keyword })
  hl("@keyword.conditional", { fg = c.keyword })
  hl("@punctuation", { fg = c.fg_muted })
  hl("@punctuation.delimiter", { fg = c.fg_muted })
  hl("@punctuation.bracket", { fg = c.fg_muted })
  hl("@punctuation.special", { fg = c.fg_muted })
  hl("@comment", { fg = c.comment })
  hl("@comment.documentation", { fg = c.comment })
  hl("@comment.error", { fg = c.error or c.fg })
  hl("@comment.warning", { fg = c.warning or c.accent })
  hl("@comment.todo", { fg = c.accent })
  hl("@comment.note", { fg = c.info or c.accent })
  hl("@markup.heading", { fg = c.accent })
  hl("@markup.quote", { fg = c.fg_muted })
  hl("@markup.math", { fg = c.accent })
  hl("@markup.link", { fg = c.accent })
  hl("@markup.link.label", { fg = c.accent })
  hl("@markup.link.url", { fg = c.string, underline = true })
  hl("@markup.raw", { fg = c.string })
  hl("@markup.list", { fg = c.fg_muted })
  hl("@markup.strong", { bold = true })
  hl("@markup.italic", { italic = true })
  hl("@markup.strikethrough", { strikethrough = true })
  hl("@tag", { fg = c.accent })
  hl("@tag.attribute", { fg = c.fg_muted })
  hl("@tag.delimiter", { fg = c.fg_muted })

  hl("FlashLabel", { fg = c.bg, bg = c.accent, bold = true })
  hl("FlashMatch", { fg = c.accent })
  hl("FlashCurrent", { fg = c.bg, bg = c.string })
  hl("FlashBackdrop", { fg = c.comment })
end

return M
